---
- name: 사용자추가
  hosts: all
  become: true
  task:
    - name: 사용자 이름생성
      user:
        name: "{{ test }}"
    - name: 패스워드 변경
      user:
        name: "{{ test }}"
        password: "{{ koscom1234 | password_hash('sha512') }}"
    - name: sudoers.d 추가
      copy:
        content: |
          %{{test} ALL=(ALL) NOPASSWD: ALL
        dest: "/etc/sudoers.d/{{test}}"
        owner: root
        group: root
        mode: 0440
        validate: "/usr/sbin/visudo -c -f '%s'"
   
